name: time_change_detector_example
description: "Demonstrates how to use the time_change_detector plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  time_change_detector:
    path: ../

  cupertino_icons: ^1.0.8
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
