name: time_change_detector_example
description: Demonstrates how to use the time_change_detector plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  time_change_detector:
    path: ../

  cupertino_icons: ^1.0.2
  awesome_notifications: ^0.6.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
