name: "Publish package to pub.dev"
on:
  release:
    types: [published]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      flutter_version: 3.24.3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get
          cd ..
      - name: Run dry run and check for errors
        run: dart pub publish --dry-run
      - name: Verify example app builds successfully
        working-directory: example
        run: flutter build apk
      - name: Publish package
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: echo "$PUB_DEV_TOKEN" | dart pub publish --force
